### ISSUE TITLE
.DS_Store

### ISSUE THREAD

**Issue by Gerzer** [MNManta/Neighborhood_Locator#1]
I saw that you deleted the `.DS_Store` file (an auxiliary file that the Finder on Mac creates to store Spotlight search indices) in an earlier commit, but your subsequent commit added it back. If you want to make sure that `.DS_Store` (or any other file) isn't ever committed, then you have to create and to commit a special `.gitignore` text file and to list each filename that you don't want to be committed, separated by newlines. Note that the "." in ".gitignore" is important: it means that you won't see it in the Finder (unless you change some settings), but you can interact with it via the Terminal.

I hope that this helps!
-Gabriel
(Remember me from Speyer?)

**Comment by MNManta** [comment]
Hi Gabriel! It's great to hear from you. That's good to know; thank you. Since it doesn't affect the program, I'm going to close the thread, but I'll make note of this for future projects.
